- ny/group3/HTML/index.html
> Primeiro commit

- ny/group3/CSS/scienceandhealth.css
- ny/group3/HTML/morenews.html
- ny/group3/HTML/scienceandhealth.html
> Nova pagina

- ny/group3/.gitignore
- ny/group3/HTML/scienceandhealth.html
- ny/group3/JS/main.js
- ny/group3/index.html
- ny/group3/package-lock.json
- ny/group3/package.json
Adição de pacotes para trabalhar com json
> Novos pacotes

- ny/group3/index.html
> Mudança Footer

- ny/group1/index.html
- ny/group1/js/moreNews.js
- ny/group1/mockup/mock-mid.js
- ny/group1/mockup/mock-moreNews.js
Foi criado dinamismo na sessão "moreNews".
> create dynamic moreNews section

- projects/crypto-currency/iluminados/api/bd.txt
- projects/crypto-currency/iluminados/api/src/routes/index.js
- projects/crypto-currency/iluminados/api/src/routes/modules/config.js
- projects/crypto-currency/iluminados/api/src/routes/modules/feeds.js
- projects/crypto-currency/iluminados/api/src/routes/modules/market.js
- projects/crypto-currency/iluminados/api/src/server.js
Criação da rota feeds, utilizando a API do site lunar crush
> feature: routeFeeds

- projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
- projects/crypto-currency/destemidos/App/src/pages/SignUp/style.js
Habilito o botão "SIGN UP" apenas quando o usuário preencher a confirmação da senha igual a senha.
Também já estruturo o front-end para receber o retorno do back-end sobre a validação se o e-mail já está cadastrado no banco ou não.
> chore: registration button

- projects/crypto-currency/destemidos/Api/routes/balance.js
- projects/crypto-currency/destemidos/Api/routes/configs/db.js
Alterei o campo id da carteira para idUser, evitando que seja confundindo o id dá carteira com id do usuário.
> chore: changing id to idUser in balance

- projects/crypto-currency/iluminados/api/src/routes/index.js
- projects/crypto-currency/iluminados/api/src/routes/modules/coin-of-the-day.js
- projects/crypto-currency/iluminados/api/src/routes/modules/feeds.js
- projects/crypto-currency/iluminados/api/src/routes/modules/influencers.js
- projects/crypto-currency/iluminados/api/src/routes/modules/login.js
- projects/crypto-currency/iluminados/api/src/routes/modules/market.js
criação da rota Feeds utilizando a API lunar crush
> feature:RouteFeeds

- projects/crypto-currency/destemidos/Api/package-lock.json
- projects/crypto-currency/destemidos/Api/package.json
- projects/crypto-currency/destemidos/Api/routes/configs/db.js
- projects/crypto-currency/destemidos/Api/routes/configs/users-validation.js
- projects/crypto-currency/destemidos/Api/routes/singin.js
- projects/crypto-currency/destemidos/Api/routes/singup.js
- projects/crypto-currency/destemidos/App/src/components/Body/index.jsx
- projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
Validação no back-end, confirmação de senha, tamanho minimo de caracteres e verificação de senhas e confirmação de senhas iguais
> chore: login

- projects/crypto-currency/destemidos/Api/routes/market.js
- projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
- projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
Mudar a tela quando o registro for feito com sucesso redirecionar para a pagina de login
> chore-register-front

- projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
- projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
- projects/crypto-currency/destemidos/App/src/pages/style.css
Melhora na visualização da tabela markets e na quantidade de moedas mostradas
> chore: table Market

- projects/crypto-currency/destemidos/Api/index.js
- projects/crypto-currency/destemidos/Api/routes/sale-coin.js
Fazendo a parte de venda das criptomoedas no back-end, alterando a quantia das moedas e do saldo do usuário.
> feature: add cryptocurrency sale

- projects/crypto-currency/destemidos/Api/routes/balance.js
- projects/crypto-currency/destemidos/Api/routes/buy-coin.js
- projects/crypto-currency/destemidos/Api/routes/sale-coin.js
Em vez de validar as compras de moedas e vendas pelo nome de cada moeda, eu faço essas validações pelo id de cada moeda.
> chore: adding validations with currency id

- projects/crypto-currency/destemidos/Api/index.js
- projects/crypto-currency/destemidos/Api/routes/profile.js
- projects/crypto-currency/destemidos/Api/routes/singin.js
Rota GET onde trás o saldo do usuário e todas criptomoedas em sua carteira e suas quantidades.
> feature: add route user profile

- projects/crypto-currency/destemidos/App/src/pages/Influencers/Style/style.css
- projects/crypto-currency/destemidos/App/src/pages/Influencers/index.jsx
- projects/crypto-currency/destemidos/App/src/pages/Markets/style.css
Adicionado titulo a pagina influencers
> titulo-influencers

- projects/crypto-currency/iluminados/app/src/components/Table/TableC/index.jsx
- projects/crypto-currency/iluminados/app/src/components/Table/TableC/styles.js
Estilização da tabela , modificação na paginação
> chore : estilização

- projects/crypto-currency/iluminados/app/src/App.js
- projects/crypto-currency/iluminados/app/src/components/Coinoftheday/index.jsx
- projects/crypto-currency/iluminados/app/src/components/Navbar/index.jsx
- projects/crypto-currency/iluminados/app/src/components/Navbar/style.js
Resolvendo conflitos que vieram apos o git pull
> Resolvendo conflitos da navbar e app

- projects/crypto-currency/destemidos/Api/routes/configs/token-validation.js
- projects/crypto-currency/destemidos/Api/routes/configs/users-validation.js
- projects/crypto-currency/destemidos/App/src/components/Destemidos/components/TransitionsPopper/index.js
- projects/crypto-currency/destemidos/App/src/components/Destemidos/index.jsx
- projects/crypto-currency/destemidos/App/src/components/Destemidos/style.css
- projects/crypto-currency/destemidos/App/src/components/TableMarket/TableBody/index.jsx
- projects/crypto-currency/destemidos/App/src/pages/Feeds/Feeds.jsx
- projects/crypto-currency/destemidos/App/src/pages/Feeds/Styles.css
- projects/crypto-currency/destemidos/App/src/pages/Feeds/index.jsx
- projects/crypto-currency/destemidos/App/src/pages/Influencers/Style/style.css
- projects/crypto-currency/destemidos/App/src/pages/Influencers/index.jsx
- projects/crypto-currency/destemidos/App/src/pages/InserirCredito/Style.js
- projects/crypto-currency/destemidos/App/src/pages/Markets/index.jsx
- projects/crypto-currency/destemidos/App/src/pages/Markets/style.css
Atualização de estilo das paginas Mercado/Feeds/Influencers
> chore: styles

- projects/crypto-currency/iluminados/app/src/components/Coinoftheday/index.jsx
- projects/crypto-currency/iluminados/app/src/components/Table/TableC/index.jsx
- projects/crypto-currency/iluminados/app/src/components/Table/TableC/styles.js
modificação na estilização , realocação de valores da tabela
> Market chore

- projects/crypto-currency/iluminados/app/src/App.js
- projects/crypto-currency/iluminados/app/src/components/Coinoftheday/index.jsx
- projects/crypto-currency/iluminados/app/src/components/Navbar/index.jsx
- projects/crypto-currency/iluminados/app/src/components/Navbar/style.js
- Protegendo as rotas, para o usuário usar apenas quando estiver logrando 
- Arrumando alguns botões da navbar
> Protegendo as rotas

- projects/generic-trello/batman/app/package-lock.json
- projects/generic-trello/batman/app/package.json
- projects/generic-trello/batman/app/src/App.js
- projects/generic-trello/batman/app/src/components/Home/index.jsx
- projects/generic-trello/batman/app/src/pages/Login/index.js
- projects/generic-trello/batman/app/src/pages/Out/index.js
- projects/generic-trello/batman/app/src/pages/Register/index.js
Criando rotas iniciais no front-end
> Feature: Criando rotas front-end

- projects/generic-trello/batman/api/package-lock.json
- projects/generic-trello/batman/api/src/index.js
- projects/generic-trello/batman/api/src/middlewares/verify-token.js
- projects/generic-trello/batman/api/src/routes/index.js
criação da função para validar o JWT
> feature: verifyToken

- projects/generic-trello/batman/api/src/controllers/Users/post.js
- projects/generic-trello/batman/api/src/models/user-schema.js
- projects/generic-trello/batman/api/src/routes/index.js
> feature: register

- projects/generic-trello/batman/api/src/controllers/Boards/post.js
- projects/generic-trello/batman/api/src/models/board-schema.js
- projects/generic-trello/batman/api/src/routes/index.js
> feature: cria board

- projects/generic-trello/batman/api/src/config/validation.js
- projects/generic-trello/batman/api/src/controllers/Users/post.js
- projects/generic-trello/batman/api/src/models/user-schema.js
- projects/generic-trello/batman/api/src/routes/index.js
finalização da rota de registro
> chore: register

- projects/generic-trello/batman/app/package-lock.json
- projects/generic-trello/batman/app/package.json
- projects/generic-trello/batman/app/public/index.html
- projects/generic-trello/batman/app/src/pages/Login/index.js
- projects/generic-trello/batman/app/src/pages/Login/styles.js
> Criando tela de login

- projects/generic-trello/batman/api/src/controllers/lists/delete.js
- projects/generic-trello/batman/api/src/controllers/lists/post.js
- projects/generic-trello/batman/api/src/models/list-schema.js
- projects/generic-trello/batman/api/src/routes/index.js
melhora na rota de lista delete e post, passando o ID fixo para testes
> chore: list

- projects/generic-trello/batman/api/src/controllers/lists/delete.js
- projects/generic-trello/batman/api/src/controllers/lists/patch.js
- projects/generic-trello/batman/api/src/controllers/lists/post.js
- projects/generic-trello/batman/api/src/routes/index.js
Listas recebendo ID por parametros agora fazendo update, delete post
> chore: lists

- projects/generic-trello/batman/app/package-lock.json
- projects/generic-trello/batman/app/package.json
- projects/generic-trello/batman/app/src/pages/Register/index.js
-Adicionando mensagem de erro na tela de registro, caso algum dos campos não seja preenchido corretamente.
> Adicionando mensagem de erro a tela de registro

- projects/generic-trello/batman/api/src/controllers/Boards/patch.js
- projects/generic-trello/batman/api/src/controllers/Boards/post.js
- projects/generic-trello/batman/api/src/middlewares/board-validate.js
- projects/generic-trello/batman/api/src/models/board-schema.js
- projects/generic-trello/batman/api/src/routes/index.js
- projects/generic-trello/batman/api/src/validation/board-validation.js
Foram feitas modificações nas rotas do board, na rota patch foi concluído a requisição de alterar título ou descrição, na rota post foi definido que o board ao ser criado ele terá o usuário que o criou como owner
> chore: atualizado rotas do board

- projects/generic-trello/superman/api/routes/list.js
Criada a rota GET das Lista pertencente ao Board
> feature: rota GET List

- projects/generic-trello/superman/api/routes/card.js
> feature: Get Cards

- projects/generic-trello/superman/app/src/components/Logout/index.jsx
- projects/generic-trello/superman/app/src/components/Logout/style.js
- projects/generic-trello/superman/app/src/pages/Profile/index.jsx
criado botão de logout, com função para remover o token
> feature: botao de logout

- projects/generic-trello/batman/api/src/controllers/lists/get.js
- projects/generic-trello/batman/api/src/controllers/lists/patch.js
- projects/generic-trello/batman/api/src/controllers/lists/post.js
- projects/generic-trello/batman/api/src/routes/index.js
> feature: list get

- projects/generic-trello/batman/api/src/controllers/Cards/delete.js
- projects/generic-trello/batman/api/src/controllers/Cards/post.js
- projects/generic-trello/batman/api/src/routes/index.js
O que foi feito?
Criação da rota para deletar Card, através do método delet, no backend
> Criada rota para deletar Card

- projects/generic-trello/batman/api/src/controllers/Cards/patch.js
- projects/generic-trello/batman/api/src/routes/index.js
O que foi feito?
Criada rota de atualização do card. Utilizando o método patch
> Criada rota de atualização

- projects/generic-trello/batman/app/src/Services/auth.js
- projects/generic-trello/batman/app/src/components/Home/index.jsx
- projects/generic-trello/batman/app/src/pages/Login/index.js
- projects/generic-trello/batman/app/src/pages/Register/index.js
Criando o arquivo auth para autenticar e proteger as rotas no front
> Criando o arquivo auth

- projects/generic-trello/superman/api/routes/board.js
- projects/generic-trello/superman/api/routes/configs/validationToken.js
- projects/generic-trello/superman/app/src/components/ContentPage/index.jsx
- projects/generic-trello/superman/app/src/components/Perfil/index.jsx
listar boards no perfil (interagindo com be)
> feature: listar boards no perfil

- projects/generic-trello/superman/api/routes/board.js
Rota para atualizar o título do quadro e também uma para atualizar os membros do quadro.
> feature: patch route in the title of the board and its members

- projects/generic-trello/batman/api/src/controllers/Boards/delete.js
- projects/generic-trello/batman/api/src/middlewares/board-validate.js
- projects/generic-trello/batman/api/src/validation/board-validation.js
Foram feitas melhoras definitivas na rota de delete, recebendo por params o ID do board que será deletado, fazendo a query no banco e retornando msg de status 200, status 404, e status 400
> chore: melhorias na rota delete

- projects/generic-trello/batman/api/src/controllers/Cards/get.js
- projects/generic-trello/batman/api/src/routes/index.js
O que foi feito?
Criado a rota no backend para o envio dos Cards para o FE
> Rota get cards

- projects/generic-trello/superman/api/routes/profile.js
- projects/generic-trello/superman/app/src/components/Menu/index.jsx
- projects/generic-trello/superman/app/src/components/Menu/style.js
- projects/generic-trello/superman/app/src/components/ModalCreateBoard/index.jsx
- projects/generic-trello/superman/app/src/components/ModalCreateBoard/style.js
- projects/generic-trello/superman/app/src/components/Perfil/index.jsx
- projects/generic-trello/superman/app/src/components/Perfil/style.js
acrescentando responsividade e alterando alumas estilizações de px para rem
> chore: acrescentando responsividade

- projects/generic-trello/batman/api/src/routes/index.js
foi adicionado a rota get no arquivo responsável pelas rotas
> chore: adiciona rota get

- projects/generic-trello/superman/api/routes/board.js
- projects/generic-trello/superman/api/routes/configs/mongo.js
- projects/generic-trello/superman/app/src/components/ContentPage/index.jsx
- projects/generic-trello/superman/app/src/components/ModalCreateBoard/index.jsx
- projects/generic-trello/superman/app/src/components/Perfil/style.js
interação do fe com be, ao criar o board ele redirecionar para a pagina do board
> chore: interação do front end com back end ao criar o board

- projects/generic-trello/batman/api/src/controllers/Users/get.js
- projects/generic-trello/batman/api/src/routes/index.js
Foi criado a rota de get all users para poder fazer a busca dos usuários registrados no programa para dicionar no board
> feature: criado rota de get para usuarios

- projects/generic-trello/batman/api/src/controllers/lists/get.js
- projects/generic-trello/batman/api/src/controllers/lists/patch.js
- projects/generic-trello/batman/api/src/routes/index.js
- projects/generic-trello/batman/api/src/swagger-output.json
melhorias nos testes feitos pelo swagger
> chore swagger

- projects/generic-trello/batman/api/src/controllers/Cards/delete.js
- projects/generic-trello/batman/api/src/controllers/Cards/patch.js
- projects/generic-trello/batman/api/src/routes/index.js
- projects/generic-trello/batman/api/src/swagger-output.json
O que foi feito?
Mudança na requisição de id através do body.
Foram alteradas nos arquivos patch, delete e também mudou o nome das rotas no arquivo index.js.
> Chore: Rota Card

- projects/generic-trello/batman/api/src/controllers/Boards/patch-unassign-user.js
- projects/generic-trello/batman/api/src/routes/index.js
Este arquivo é responsável por retirar a assinatura do usuário, o usuário é enviado através da requisição do front-end e o id do board através de params
> feature: cria novo arquivo patch-unassign-user.js

- projects/generic-trello/batman/api/src/controllers/Users/profile.js
- projects/generic-trello/batman/api/src/routes/index.js
- projects/generic-trello/batman/app/src/components/Board/index.js
- projects/generic-trello/batman/app/src/components/Header/index.js
- projects/generic-trello/batman/app/src/components/Header/styles.js
- projects/generic-trello/batman/app/src/pages/Login/index.js
Cração de uma rota de perfil para o usuario
> feature: route profile

- projects/generic-trello/batman/app/package-lock.json
- projects/generic-trello/batman/app/package.json
- projects/generic-trello/batman/app/src/components/Form-List/index.js
- projects/generic-trello/batman/app/src/components/ModalBoard/index.jsx
- projects/generic-trello/batman/app/src/components/ModalBoard/styles.js
- projects/generic-trello/batman/app/src/pages/Home/index.jsx
- projects/generic-trello/batman/app/src/pages/Home/styles.js
- projects/generic-trello/batman/app/src/pages/Login/index.js
foi criado um component novo chamado ModalBoard que é responsável por criar um novo modal, assim que o usuário registra os dados exigidos e clica em salvar, o modal é fechado e a tela atualizada com o novo board presente. Foi usado uma biblioteca chamada react-modal e styled component
> feature: criado modal para criar board

- projects/generic-trello/batman/app/src/components/Board/index.js
- projects/generic-trello/batman/app/src/components/Home/index.jsx
- projects/generic-trello/batman/app/src/components/List/index.js
- projects/generic-trello/batman/app/src/components/List/styles.js
- projects/generic-trello/batman/app/src/pages/Home/index.jsx
foi realizado uma modificação que antes impossibilitava de criar lista quando não tivesse nenhuma lista registrada no board, agora é possível adicionar lista mesmo não tendo nenhuma lista no board
> chore: melhora acao de add new list

- projects/generic-trello/batman/app/src/components/Card/styles.js
- projects/generic-trello/batman/app/src/components/Form-List/style.js
- projects/generic-trello/batman/app/src/components/Header/index.js
- projects/generic-trello/batman/app/src/components/Header/styles.js
- projects/generic-trello/batman/app/src/components/List/index.js
- projects/generic-trello/batman/app/src/components/List/styles.js
- projects/generic-trello/batman/app/src/styles/global.js
Ajustes de indentação nos arquivos style.js;
Alterando a cor do botão de nova lista para não confundir com o botão de adicionar card;
Alterando o formulário de nova lista para abrir no centro da página tanto quanto no computador quanto no celular;
> Chore: Ajustes de estilo

- projects/generic-trello/batman/app/src/components/Board/index.js
- projects/generic-trello/batman/app/src/components/Board/styles.js
- projects/generic-trello/batman/app/src/components/Card/styles.js
- projects/generic-trello/batman/app/src/components/Header/index.js
- projects/generic-trello/batman/app/src/components/Header/styles.js
- projects/generic-trello/batman/app/src/components/List/styles.js
- projects/generic-trello/batman/app/src/styles/global.js
foram feitas algumas melhorias na UI para ficar mais agradável aos usuários.
> chore: melhorado ui

- projects/generic-trello/batman/app/src/components/Board/index.js
- projects/generic-trello/batman/app/src/components/List/index.js
Criação de um botão que remove listas
> button-remove-list

- projects/generic-trello/batman/app/src/components/Header/styles.js
O último commit houve alguns erros, onde algumas importações foram excluidas na hora da resolução de conflitos
> fix: resolvido alguns erros do último commit

- projects/generic-trello/batman/app/src/components/Card/index.js
- projects/generic-trello/batman/app/src/components/Card/styles.js
> featur: button remove card

- projects/generic-trello/batman/app/src/pages/Register/index.js
Ao tentar registrar um usuário aparecia um erro e crashava o programa, foi resolvido esse erro e o registro agora segue o fluxo de enviar o usuário para a página de login após o registro
> bugfix: remove erro ao registrar usuario

- projects/generic-trello/batman/app/src/pages/Home/index.jsx
- projects/generic-trello/batman/app/src/pages/Home/styles.js
Criado um botão que remove os boards
> feature: button remove board
